name: Good First
description: Publish a good first issue labels good first issue
labels: kind/good first issue
body:
  - type: textarea
    id: whoJoin
    attributes:
      label: Who can join or take the task?
      description: |
        The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.
        After a contributor has successfully completed 1-2 good first issue's,
        they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

  - type: textarea
    id: howToJob
    attributes:
      label: How to join or take the task?
      description: |
        Just reply on the issue with the message `/assign` in a separate line.
        Then, the issue will be assigned to you.

  - type: textarea
    id: howToAsk
    attributes:
      label: How to ask for help?
      description: |
        If you need help or have questions, please feel free to ask on this issue.
        The issue author or other members of the community will guide you through the contribution process.